### ISSUE TITLE
`Gravatar::URL` not in prereq list

### ISSUE THREAD

**Issue by xsawyerx** [charsbar/acme-cpanauthors#4]
This [Changes](https://metacpan.org/source/ISHIGAKI/Acme-CPANAuthors-0.25/Changes#L27) file entry Indicates that `Gravatar::URL` was added to recommended prereqs. It was added to the `cpanfile` ([here](https://metacpan.org/source/ISHIGAKI/Acme-CPANAuthors-0.25/cpanfile#L14)), but the META file (generated by [ExtUtils::MakeMaker::CPANfile](https://metacpan.org/pod/ExtUtils::MakeMaker::CPANfile)) ignores the `recommended`, which resulted in `Gravatar::URL` not declared anywhere in the actual [META](https://metacpan.org/source/ISHIGAKI/Acme-CPANAuthors-0.25/META.json#L22) file.

**Comment by charsbar** [comment]
Thanks for the input. Fixed ExtUtils::MakeMaker::CPANfile and shipped its 0.07, and shipped also Acme::CPANAuthors 0.26 with fixed META files.

**Comment by xsawyerx** [comment]
Thank you! :)
